name: Atualizar Pac-Man Contribution

on:
  schedule:
    - cron: "0 0 * * 0"   # todo domingo meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Gerar gráfico Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: m4thi4ss
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
